# Generated by Django 3.1.5 on 2021-01-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
