# Generated by Django 3.1.5 on 2021-01-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20210120_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
